apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 850195140598.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 850195140598.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 58f4520b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
